name: 'Laravel deploy action'
description: 'Automatically deploy your Laravel application to remote server'
inputs:
  host: 
    description: 'The remote server ip, support IPV4 only'
    required: true
  username:
    description: 'The ssh login user name'
    required: true
  password:
    description: 'The ssh login password'
    required: true
  app_env_data:
    description: 'The environment variable for application, will be written into .env file'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer:v2
        extensions: ssh2

    - name: Deploy
      env:
        HOST: ${{ inputs.host }}
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
        APP_ENV_DATA: ${{ inputs.app_env_data }}
      shell: bash
      run: php ${{ github.workspace }}/deploy.php