name: Deoloy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: A Laravel deploy action example
    steps:
      - name: test
        uses: yankewei/laravel-deploy-action@main
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          app_env_data: ${{ secrets.APP_ENV_DATA }}